### ISSUE TITLE
TF Explorer Wiki Link

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#42] opened 2022-03-17 10:52 UTC
According to test case [TC235](https://app.testlodge.com/a/26076/projects/40893/suites/193853expand_section=305792#case_3354998) there should be a to get started wiki link in the explorer but there isn't.

**Comment by RafyAmgadBenjamin** [comment] 2022-03-17 14:21
this is a duplicate of this issue 
https://github.com/threefoldtech/tfgrid_dashboard/issues/41

**Closed as completed** 2022-03-17 15:32 UTC
