### ISSUE TITLE
[Bug 🐞]: Unable to reach some nodes on devnet even though they appear as up in the explorer

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#387] opened 2023-03-06 09:33 UTC
### What happened?

Some nodes on devnet (Nodes: 16, 19, 29) are appearing as up in the dashboard but from the weblets they appear as down and i was unable to deploy on these nodes from tsclient. as seen below their status is up in the dashboard:

![image](https://user-images.githubusercontent.com/101194226/223069509-d3b56a27-1361-4c19-bda6-38763c24b550.png)

### Node 16

![image](https://user-images.githubusercontent.com/101194226/223068297-9322db0c-6b1f-4e14-9b0d-1f43579574ea.png)

![image](https://user-images.githubusercontent.com/101194226/223068460-498c00ab-fd91-43aa-b41c-c92d6cb6d3bc.png)

### Node 19

![image](https://user-images.githubusercontent.com/101194226/223068710-c4c49868-9dce-4342-b400-31f622659d7d.png)

![image](https://user-images.githubusercontent.com/101194226/223068602-2c80e3d1-018c-4c42-bdaf-626c270a288f.png)

### Node 29

![image](https://user-images.githubusercontent.com/101194226/223069307-d52f9e40-bd8a-4688-9a67-a36d2e240419.png)

![image](https://user-images.githubusercontent.com/101194226/223068952-852c38cd-450e-4180-95bd-d922fa247f10.png)

### What did you expect?

The nodes should respond from the weblets and tsclient or be reported as down in the dashboard if it's actually not working.

### What browsers are you seeing the problem on?

Chrome

**Comment by xmonader** [comment] 2023-03-08 10:43
The dashboard online/offline decision is based on the uptime of the node, while the message node is down in weblets, is happening because we actually tried to ping the node over the RMB, which failed because of e2e support https://github.com/threefoldtech/grid_weblets/issues/1333

i'll close this as duplicate of #1333

**Closed as completed by xmonader** 2023-03-08 10:43 UTC
Labels: type_bug
