### ISSUE TITLE
Play profiles dissappeared on test net for mutiple users 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#324] opened 2022-11-13 16:19 UTC
https://github.com/threefoldtech/test_feedback/issues/294

![image](https://user-images.githubusercontent.com/44621168/201532282-5a472d23-ff30-49ca-9b97-b620df2fdd37.png)

i didnt clear cache, storage or anything. 

prior report of similar situation 
https://github.com/threefoldtech/test_feedback/issues/294

**Comment by Parkers145** [comment] 2022-11-13 16:52
i am unable to access the entirety of the threefoldcloud vms from my profile on recreation

**Comment by Parkers145** [comment] 2022-11-13 18:06
![image](https://user-images.githubusercontent.com/44621168/201537019-beb71a97-7417-4c75-ab6b-8870d439831c.png)
![image](https://user-images.githubusercontent.com/44621168/201537035-1b26130b-4972-4776-8d86-7a94d535c521.png)

all of the vms are still fully functional, just not in my profile anymore, and my balance doesnt seem to be reducing
![image](https://user-images.githubusercontent.com/44621168/201537222-433803c0-e59c-4aee-b7d5-550066137064.png)

**Comment by Parkers145** [comment] 2022-11-13 18:06
twin id for the deployments is 581

**Comment by Parkers145** [comment] 2022-11-13 18:11
15293 is the contract for the ip serving social 
mail is on  185.206.122.163 on node 19 i believe 
15314 is the contract for the ip serving music
15319 is the contract for the ip serving videos

**Comment by despiegk** [comment] 2022-11-13 18:27
a chat has been started with main engineers for this topic, we will try to find the root cause asap, thank you for detailed report.

whoever wants to join this chat its on https://t.me/+Fdb54XBxAPtmYjc8

**Comment by Parkers145** [comment] 2022-11-13 23:07
![image](https://user-images.githubusercontent.com/44621168/201549357-55299735-2f8f-44e9-acdf-8a97275a2c62.png)
this appears to have affected main net aswell as I no longer have a profile there.

**Comment by AhmedHanafy725** [comment] 2022-11-14 10:41
> twin id for the deployments is 581

checked this twin id, it doesn't have any contracts 

> 15293 is the contract for the ip serving social 
> 15314 is the contract for the ip serving music
> 15319 is the contract for the ip serving videos

these contracts are deployed with twin id 667, it's a different account

for the profiles that disappeared, weblets stores a key on the local storage on the browser. weblets doesn't delete this key, but if the user deletes it, the profiles will disappear. So please can you check if the browser got changed or if its config got removed by any chance?

![image](https://user-images.githubusercontent.com/41957921/201637516-35aed5cd-5c83-4804-a878-b136fd207b11.png)

**Comment by Parkers145** [comment] 2022-11-14 13:38
> > twin id for the deployments is 581
> 
> 
> 
> checked this twin id, it doesn't have any contracts 
> 
> 
> 
> > 15293 is the contract for the ip serving social 
> 
> > 15314 is the contract for the ip serving music
> 
> > 15319 is the contract for the ip serving videos
> 
> 
> 
> these contracts are deployed with twin id 667, it's a different account
> 
> 
> 
> for the profiles that disappeared, weblets stores a key on the local storage on the browser. weblets doesn't delete this key, but if the user deletes it, the profiles will disappear. So please can you check if the browser got changed or if its config got removed by any chance?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/41957921/201637516-35aed5cd-5c83-4804-a878-b136fd207b11.png)
> 
> 

I'm unsure how the twin id for the deployments would be 667, but i used the same mnemonics to recover my profile and got 581. 

I had been logged in working on my stuff, went to bed, robertl asking about missing profiles woke me up, I looked and My own were gone to. I guess it's possible somehow these deployments ended up under My other polka extension? I'll try creating a account with those words, but I specifically wrote down what keys I was using for these deployments 


Twin id 667 is definitely the twin that is typically with my threefoldtutorials polkadot extension, but this doesn't make sense because that twin has 0 tft in it, and my Parker's polka extension is on twin 581, but has the tft that was paying for those deployments

**Comment by Parkers145** [comment] 2022-11-14 14:00
> 
> these contracts are deployed with twin id 667, it's a different account
> 

your correct, i have found them, but i have no idea how they ended up here. i certainly didnt intend to tie my mastadon deployments to my tutorials twin. im very confused about how the log in system for the playground works now, does it interact with the polkadot-extension at all? i appears the disappearance was bad bookkeeping on my part,  i still dont understand why myself, teis and robert all lost our profiles at the same time though, would it be possible for this to move to a login system that doesnt rely on local storage? 

![image](https://user-images.githubusercontent.com/44621168/201678542-2781320a-740f-4bcf-b967-20b5f2e91f39.png)

**Comment by AhmedHanafy725** [comment] 2022-11-14 15:22
the playgrounds are not interacting with the Polkadot extension at all. you enter the mnemonics (you had created with the Polkadot extension and activated with the dashboard) on the profile manager to create profiles and the active one will be used for the deployments.
![image](https://user-images.githubusercontent.com/41957921/201693000-1bef8b91-7fef-46b3-9356-2c0b187602a2.png)

> would it be possible for this to move to a login system that doesnt rely on local storage?

right now, there is no plan to change it

### How it works
it's just a key on the local storage encrypted with your password. it's created/updated with the creation/modification of the profiles.

### How to avoid losing it
- please don't delete the local storage of your browser (**Note**: clearing the cache won't remove this storage)
- please don't remove the data on the roaming directory of the browser on your device (on Linux: ~/.config/google-chrome)

**Notes:** 
- using a different user on the machine, won't see this key
- using a different browser or even an incognito window on the same browser, won't see this key as well

**Comment by Parkers145** [comment] 2022-11-14 15:29
as ive said here an in my previous issue, these keys disappear without deleting local storage, I have had to walk multiple users through recreating their profile while they have small heart attacks thinking their work has disappeared. I feel i am likely one of the more versed non team members in the playground, and i struggle to teach people to use this login system. 

if my understanding is correct, I am to believe that 3 seperate users in 3 seperate countries all accidentally deleted their local storage at the same time?

why can i not access the playground from multiple computers without having to carry a copy of seed phrases with me everywhere i go, this is a nightmare for me, i travel for work, i really dislike having my entire book of phrases with me at all times.

**Comment by AhmedHanafy725** [comment] 2022-11-14 16:04
> as ive said here an in my previous issue, these keys disappear without deleting local storage, I have had to walk multiple users through recreating their profile while they have small heart attacks thinking their work has disappeared. I feel i am likely one of the more versed non team members in the playground, and i struggle to teach people to use this login system.

I understand. But no one should be worried if he lost the profiles as long as he has the mnemonics, he will be able to restore the profile with it.

> if my understanding is correct, I am to believe that 3 seperate users in 3 seperate countries all accidentally deleted their local storage at the same time?

that's really weird. I had this key in my local storage for almost a year, and it didn't disappear either once.

> why can i not access the playground from multiple computers without having to carry a copy of seed phrases with me everywhere i go, this is a nightmare for me, i travel for work, i really dislike having my entire book of phrases with me at all times.

that's for the user's security, this seed carries your tokens and it doesn't leave the user's browser, it's just used to sign your requests.

**Comment by despiegk** [comment] 2022-11-15 05:00
see how to resolve https://github.com/threefoldtech/home/issues/1343
current situation is for sure not good enough

**Comment by xmonader** [comment] 2022-11-17 12:05
closing in favor of https://github.com/threefoldtech/home/issues/1343

**Closed as completed by xmonader** 2022-11-17 12:05 UTC
Labels: priority_major
