### ISSUE TITLE
node 219 not deploying applets properly 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#328] opened 2022-11-15 21:08 UTC
![image](https://user-images.githubusercontent.com/44621168/202023719-b6350975-1467-46da-9894-5e7f7a00b219.png)

when deploying the applets on 219 i get bad gateway when i attempt to connect, everything else seems to functioning and i have checked and recheked the public config and dns records. 

![image](https://user-images.githubusercontent.com/44621168/202024043-093bd611-67f7-4944-a664-08eb97f3d93b.png)

![image](https://user-images.githubusercontent.com/44621168/202024129-1c266ed0-eff8-45a4-b0fa-8ebedc70dd8c.png)
![image](https://user-images.githubusercontent.com/44621168/202024184-a6d64e2f-c1de-4a33-8e15-292eb4b69a3f.png)
![image](https://user-images.githubusercontent.com/44621168/202024250-a325d0cf-6aec-4953-ba31-b622c06a0d33.png)
![image](https://user-images.githubusercontent.com/44621168/202024335-9b495d63-a306-454b-aff5-cccfc05a08e3.png)
![image](https://user-images.githubusercontent.com/44621168/202025360-28ba5162-da81-4460-9c4e-913613f1462d.png)
![image](https://user-images.githubusercontent.com/44621168/202025506-8db3bb25-04cc-446e-935b-e7b2c48d2ff9.png)

the node is deploying addresses fine, and everything else seems to be working,

**Comment by xmonader** [comment] 2022-11-20 15:16
@coesensbert please review his setup when possible

**Comment by coesensbert** [comment] 2022-11-21 16:45
Public config for node 219 is 100% correct.

Could reproduce the issue on the same node, though things worked after around 15min after the deployment.
It just seem to take a while for the vm to start up, and quite some time for mattermost services to start inside the micro vm.
The slowness could be related to old hardware / slow or malfunctioning ssd (just a guess)

https://mm288delme.gemini.tfcloud.us/
http://[301:9970:5ee:bbce:a88d:2439:b31f:e4e3]:8000

@Parkers145 could you retry and wait ~15 to 20min to test the FQDN provided by the deployment

**Comment by Parkers145** [comment] 2022-11-21 22:22
219 is running 2x 2690v2 and 256 gb of ram and sata ssds, they are all name brand and benchmarked recently, do you think that hardware would cause this?

**Comment by coesensbert** [comment] 2022-11-22 14:05
Not clear why it was so slow on that node but could not reproduce it on our Testnet nodes (which are also old). Same for mainnet, tested 2 mattermost deploys and the workload was immediately available trough the provided url.
We also looked on your ZOS node logs for error's or issues but found none, after a while the vm and mattermost service got loaded. Everything works and was setup correctly, it was just slow.
Deployed another mattermost workload on node 219 today, this was also fast and without issues. They are still available here:
- https://mm288delme.gemini.tfcloud.us/
- https://mm288delme2.gemini.tfcloud.us/

One theory was that the flist needed downloading, but since the node already deployed mattermost in the past it has the flist data in it's cache.
We don't have ZOS metrics yet for tesnet, but on one of your devnet nodes we saw quite some iowait on the ssd's for a while, depending on the workload it could point to some ssd related issues though there are also applications that could generate this.
![image](https://user-images.githubusercontent.com/88312671/203333828-b2107733-883c-4585-ad88-520fed1012ff.png)

**Comment by Parkers145** [comment] 2023-02-07 17:49
this is still Occurring on both of my test net nodes and my main net node and all nodes have had full diags run recently, can we re-open this and see if we can get these working i have a ton of domains ive purchased to give all the nodes root domains to make for a better use experience but i cant suggest people use them while also saying they will be broke for awhile at the start.

**Comment by coesensbert** [comment] 2023-02-08 09:21
Could you give the node ID's for test and main?

**Comment by Parkers145** [comment] 2023-02-08 11:57
219 on test net and 5341 on main

**Comment by xmonader** [comment] 2023-02-26 04:31
@coesensbert what is the status here?

**Comment by coesensbert** [comment] 2023-02-27 16:05
Oops, forgot about this one. Will do some tests again to see if I can find something

**Comment by coesensbert** [comment] 2023-04-26 08:14
Could not reproduce since my last attempt. Wanted to have another look but both nodes seem to be offline, is this normal @Parkers145 ? We close this one or you have some other nodes where this also happens?

**Comment by Parkers145** [comment] 2023-04-26 12:45
It can close

**Closed as completed** 2023-04-26 14:37 UTC
Labels: type_bug
