### ISSUE TITLE
can't access metrics after deploy QSFS by terraform

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#61] opened 2022-04-04 10:23 UTC
with devnet i deployed a qsfs and after deploy success i can ssh into vm but can't access metrics

https://github.com/threefoldtech/terraform-provider-grid/issues/141

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/54

**Comment by rkhamis** [comment] 2022-04-21 10:24
duplicate of #31

**Closed as completed by rkhamis** 2022-04-21 10:24 UTC
