### ISSUE TITLE
Node lost "reserved" status

### ISSUE THREAD

**Issue by s-areal** [threefoldtech/test_feedback#325] opened 2022-11-14 11:25 UTC
As I was checking the capacity of reserved node, i realized the node does not shows as reserved anymore. 
Interesting is that this node 191, is still available for deployments....
Last action that I can remember after seeing this was to delete a Caprover deployment -  don't know if this could be related.

Note that it is also possible to choose over resources from the menu. I'm choosing a 600GB of SDD space out of 477GB possible and I still get the message - "Node(191) is up and has enough resources.", which is not true.

![Captura de ecrã 2022-11-14, às 11 25 19](https://user-images.githubusercontent.com/49781569/201648372-0e06ebf0-3097-4de6-9349-a4c2595a64dc.png)

on the other side, I have 16GB or RAM available, and I can only choose 13000MB

![Captura de ecrã 2022-11-14, às 11 24 23](https://user-images.githubusercontent.com/49781569/201648220-5c9290cf-c8db-4502-a465-178a16bec044.png)

**Comment by s-areal** [comment] 2022-11-14 11:33
I just reserved the node again FYI

**Comment by DylanVerstraete** [comment] 2022-11-21 08:19
I don't even know where to start debugging for this issue. Could it be that it's only client side related? 
Can you reserve a node and try deploy on it with terraform?

**Comment by DylanVerstraete** [comment] 2022-11-21 09:02
@mohamedamer453 is this a duplicate of: https://github.com/threefoldtech/test_feedback/issues/317 ?

**Comment by mohamedamer453** [comment] 2022-11-21 09:26
I'm not sure if this is the same issue, and also i wasn't able to reproduce it since node `191` is currently not rentable. 

> Last action that I can remember after seeing this was to delete a Caprover deployment - don't know if this could be related.

the only thing that came to my mind from the description of the issue is that there was an issue with the weblets were the delete all button also deletes rent contracts https://github.com/threefoldtech/grid_weblets/issues/1027 it was fixed and verified on devnet, however it's still not released on mainnet,

**Comment by A-Harby** [comment] 2022-11-21 14:21
After reserving a node and trying to deploy and delete some contract, all seems to be fine.
But when I used `Delete all` button in the weblets all my contracts deleted included both node contracts as well as rent contracts. 
![image](https://user-images.githubusercontent.com/109473873/203077848-d9dbff20-8faa-4601-a5fd-f316f0856305.png)

Before using `Delete all` button.
![image](https://user-images.githubusercontent.com/109473873/203077567-d0a92edf-41c8-4ec4-a1e3-1508cde7b8ad.png)
After using it.
![image](https://user-images.githubusercontent.com/109473873/203077657-95ec2981-259f-4eec-95ba-27c788fda434.png)
 
So indeed the issue is related to https://github.com/threefoldtech/grid_weblets/issues/1027, and have been solved but not released yet on the mainnet.

**Closed as completed by A-Harby** 2022-11-21 14:21 UTC
Labels: type_bug
